---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: audio-to-text-j1731928799699
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-to-text-j1731928799699 
  name: audio-to-text-j1731928799699
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi