apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: audio-to-text-j1731928799699
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: audio-to-text-j1731928799699 
  name: audio-to-text-j1731928799699
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: audio-to-text-j1731928799699 
